version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/steam-gametime-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    build:
      context: ./backend/Steam API
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:4567
    networks:
      - app-network

networks:
  app-network:
    driver: bridge